name: Release

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          accept-flake-config = true
    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: |
        nix build
    - name: Create release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref }} ./result/bin/zwift.wasm --title "Release ${{ github.ref }}" --notes "Release ${{ github.ref }}"
